name: taski
description: "Mobile code challenge"

version: 1.0.0+1

environment:
  sdk: ^3.6.1

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  flutter_svg: ^2.0.17
  fpdart: ^1.1.1
  auto_size_text: ^3.0.0
  google_fonts: ^6.2.1
  flutter_spinkit: ^5.2.1
  shimmer: ^3.0.0
  camera: ^0.11.1
  file_picker: ^8.1.7
  image_picker: ^1.1.2
  image_cropper: ^8.1.0
  sqflite: ^2.4.1
  flutter_modular: ^6.3.4

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0

flutter:

  uses-material-design: true
  assets:
    - assets/icons/svg/